Repository Sethioss/ICAN-Card-Game, pull requests merged in 2024-11, with the labels that each got.

#9 Set CardData to correspond to the game's design
  Content/Blueprint/Cards/BP_Fire_Card.uasset
  Content/Blueprint/S_CardStruct.uasset
  Content/Blueprint/Score/Rules/BP_Always_True.uasset
  Content/Blueprint/Score/Rules/BP_CardDataSample.uasset
  Source/ICAN_Card_Game/CardData.h
Labels: Feature

#6 Levels
  Content/Maps/Lighting_Level.umap
  Content/Maps/Visual_Level.umap
Labels: Misc

#7 Ajout widget timer
  Content/Blueprint/Cards/BP_BlueCard.uasset
  Content/Blueprint/Widget/WBP_Test.uasset
  Content/Visuals/Fonts/DefaultTextMaterialOpaque_Dino.uasset
Labels: Art integration

#10 Ajout map test ga
  Content/Blueprint/Cards/BP_Fire_Card_test.uasset
  Content/Blueprint/Cards/Test_GA/BP_Fire_Card_test.uasset
  Content/Blueprint/Cards/Test_GA/BP_Fire_Card_test1.uasset
  Content/Maps/Level_Test.umap
  Content/Visuals/Materials/Cards/M_Textured_Card_Inst.uasset
  Content/Visuals/Materials/Enviro/M_Background.uasset
  Content/Visuals/Materials/Enviro/M_Floor.uasset
  Content/Visuals/Meshes/Character/Character_Placeholder.uasset
  Content/Visuals/Meshes/Character/M_characterPlaceholder.uasset
  Content/Visuals/Meshes/Character/M_characterPlaceholder1.uasset
  Content/Visuals/Meshes/Character/M_characterPlaceholder2.uasset
  Content/Visuals/Meshes/Enemy/Ennemy_Placeholder.uasset
  Content/Visuals/Meshes/Enemy/M_Enemy.uasset
  Content/Visuals/Textures/Cards/Card02_UV.uasset
Labels: Art integration
