Repository Sethioss/ICAN-Card-Game, pull requests merged in 2024-10, with the labels that each got.

#3 icon and font added
  Content/Blueprint/Cards/BP_BlueCard.uasset
  Content/Blueprint/Cards/BP_Fire_Card.uasset
  Content/Blueprint/Cards/BP_Fire_Card_test.uasset
  Content/Blueprint/Cards/BP_StandardCard.uasset
  Content/Maps/FirstSceneLevel.umap
  Content/Visuals/Fonts/DefaultTextMaterialOpaque_Dino.uasset
  Content/Visuals/Fonts/Dinofont.uasset
  Content/Visuals/Fonts/Dinofont_Font.uasset
  Content/Visuals/Materials/Cards/Icon/M_Icon.uasset
  Content/Visuals/Materials/Cards/Icon/M_Icon_Fire.uasset
  Content/Visuals/Materials/Cards/Icon/M_Icon_Water.uasset
  Content/Visuals/Materials/Cards/Icon/Textures/Fire_Icon.uasset
  Content/Visuals/Materials/Cards/Icon/Textures/Water_Icon.uasset
  Content/Visuals/Materials/Cards/M_Textured_Card.uasset
Labels: Art integration

#5 Disabled FMOD as it was causing issues with opening the project
  ICAN_Card_Game.sln.DotSettings.user
  ICAN_Card_Game.uproject
Labels: Misc

#8 Sebastien/score calculation accurate
  Content/Blueprint/BP_ScoreCalculator.uasset
  Content/Blueprint/Score/Bonus/BP_Add3.uasset
  Content/Blueprint/Score/Bonus/BP_AddCardNumAsValue.uasset
  Content/Blueprint/Score/Bonus/BP_AddRandom.uasset
  Content/Blueprint/Score/Bonus/BP_Multiply3.uasset
  Content/Blueprint/Score/Bonus/BP_NullBonus.uasset
  Content/Blueprint/Score/Bonus/BP_RandomBonus.uasset
  Content/Blueprint/Score/Operands/BP_Addition.uasset
  Content/Blueprint/Score/Rules/BP_Always_False.uasset
  Content/Blueprint/Score/Rules/BP_Always_True.uasset
  Content/Blueprint/Score/Rules/BP_Pair_Rhyme.uasset
  Content/Maps/FirstSceneLevel.umap
  ICAN_Card_Game.sln.DotSettings.user
  ICAN_Card_Game.uproject
  Source/ICAN_Card_Game/Card.h
  Source/ICAN_Card_Game/CardCollectionsManager.cpp
  Source/ICAN_Card_Game/CardData.h
  Source/ICAN_Card_Game/CardSlotComponent.cpp
  Source/ICAN_Card_Game/PlayedCardMat.cpp
  Source/ICAN_Card_Game/PlayedCardMat.h
  Source/ICAN_Card_Game/ScoreBonus.cpp
  Source/ICAN_Card_Game/ScoreBonus.h
  Source/ICAN_Card_Game/ScoreBonusOperand.cpp
  Source/ICAN_Card_Game/ScoreBonusOperand.h
  Source/ICAN_Card_Game/ScoreCalculator.cpp
  Source/ICAN_Card_Game/ScoreCalculator.h
  Source/ICAN_Card_Game/ScoreRule.cpp
  Source/ICAN_Card_Game/ScoreRule.h
Labels: Feature
